<a href="https://colab.research.google.com/github/lostinrepo/Deep-Learning/blob/master/artificial_neural_network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [0]:
tf.__version__

'2.2.0'

In [0]:
data = pd.read_csv('bank_data.csv')
data.head()
X=data.iloc[:, 3:-1].values
y=data.iloc[:,-1].values

In [0]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [0]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [0]:
# encoding for geography 
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [17]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [0]:
# scaling data 
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [0]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [0]:
ann=Sequential()
ann.add(Dense(5, activation='relu')) # input layer and first hidden layer
ann.add(Dense(5, activation='relu')) # second hidden layer
ann.add(Dense(1, activation='sigmoid')) # output layer

In [0]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy']) #compiling 

In [22]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100) # training 

Epoch 1/100
250/250 [==============================] - 0s 1ms/step - loss: 0.5865 - accuracy: 0.7200
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4810 - accuracy: 0.7960
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4481 - accuracy: 0.7960
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4330 - accuracy: 0.8008
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4249 - accuracy: 0.8138
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4193 - accuracy: 0.8186
Epoch 7/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4145 - accuracy: 0.8211
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4103 - accuracy: 0.8245
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4068 - accuracy: 0.8250
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4037 - accura

In [23]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

[[False]]


In [24]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Making the Confusion Matrix

In [25]:
from sklearn.metrics import confusion_matrix, accuracy_score
print(confusion_matrix(y_test, y_pred))
accuracy_score(y_test, y_pred)

[[1510   85]
 [ 199  206]]


0.858